---
# tasks file for nginx
- include: "install-nginx-{{ansible_distribution}}.yml"
- include: "configure-nginx-{{ansible_distribution}}.yml"
- include: common-configure.yml
- include: common-deploy.yml
